name: Metanthropes Automated Code Builder
on: push
jobs:
  runvm:
    name: Spin off a VM to run the build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the master branch
      uses: actions/checkout@v3
    - name: Install NPM dependencies
      run: npm install
    - name: Compile SCSS with gulp
      run: npm run compile
    - name: Upload the compiled files
      uses: actions/upload-artifact@v3
      with:
        name: compiledcss
        path: .next/