name: Metanthropes Automated Build & Release
on: push
jobs:
  build:
    name: Metanthropes Automated Builder
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the master branch
      uses: actions/checkout@v3
    - name: Install NPM dependencies
      run: npm install
    - name: Compile SCSS with gulp
      run: npm run compile
    - name: Get Version Number
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'system.json'
        prop_path: 'version'
    - name: Debug-print Version Number
      run: echo ${{steps.version.outputs.prop}}
    - name: Set Download Link
      uses: jossef/action-set-json-field@v2
      with:
        file: './system.json'
        field: 'download'
        value: "https://github.com/${{github.repository}}/releases/download/${{steps.version.outputs.prop}}/metanthropes.zip"
    - name: Zip the compiled files
      uses: thedoctor0/zip-release@0.7.2
      with:
        type: 'zip'
        filename: 'metanthropes.zip' # I need to make the name to match the release name / version name of the build --- oooor just name it metanthropes.zip and be done with it
        exclusions: '*.git* /*node_modules/* /*.vscode/* .npmignore .nvmrc .gulpfile.js .package-lock.json .package.json /scss/*'
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{steps.version.outputs.prop}}
        name: Metanthropes - Version ${{steps.version.outputs.prop}}
        body: ${{ github.event.release.body }}
        draft: false
        prerelease: false
        files: |
          metanthropes.zip
          system.json