name: NodeJS with Gulp

on:
  push:
    branches: [ "master" ]
    tags:
     - "*"

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS 17
        uses: actions/setup-node@v3
        with:
          node-version: "17"
          
      - name: Install node modules
        run: npm install
        
      - name: Gulp
        run: npm run gulp
        
      - name: Get System ID
        id: systemID
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'system.json'
          prop_path: 'id'
          
      - name: Get tag    
        id: tag
        uses: dawidd6/action-get-tag@v1.1.0

      - name: Create ZIP
        run: |
          cd build
          zip -r ../${{steps.systemID.outputs.prop}}.zip *
          
      - name: Set Download Link
        uses: jossef/action-set-json-field@v2
        with:
          file: './system.json'
          field: 'download'
          value: "https://github.com/${{github.repository}}/releases/download/${{steps.tag.outputs.tag}}/${{steps.systemID.outputs.prop}}.zip"
          
      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          
      - name: Create Release
        uses: ncipollo/release-action@v1.9.0
        with:
          token: ${{ secrets.PAT }}
          artifacts: "./system.json, ./${{steps.systemID.outputs.prop}}.zip"
          body: ${{ steps.changelog.outputs.changelog }}
          draft : true
          generateReleaseNotes : true
